import React from "react";
import { Metadata } from "next";
import Script from "next/script";
import Link from "next/link";
import Image from "next/image";
import ScrollSpyNav from "@/components/ScrollSpyNav";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Income Tax Notice Help: Section 143(1) & 148 Remedies | AMAConnect",
  description:
    "A step-by-step guide on handling tax scrutiny notices, drafting responses to Section 143(1) discrepancies or Section 148 reassessments, and filing online appeals.",
  keywords: "income tax notice section 148 India, reply to section 143 1 notice, income tax appeal online process, reassessment notice time limit, tax scrutiny reply format, faceless assessment scheme",
  alternates: {
    canonical: "https://amaconnect.in/income-tax-notice-section-148-appeal-remedies-guide",
  },
  openGraph: {
    title: "Income Tax Notice Help: Section 143(1) & 148 Remedies",
    description:
      "A step-by-step guide on handling tax scrutiny notices, drafting responses to Section 143(1) discrepancies or Section 148 reassessments, and filing online appeals.",
    url: "https://amaconnect.in/income-tax-notice-section-148-appeal-remedies-guide",
    siteName: "AMA Legal Solutions",
    type: "website",
  },
};

export default function IncomeTaxNoticeGuidePage() {
  const baseUrl = "https://amaconnect.in";
  const pageUrl = `${baseUrl}/income-tax-notice-section-148-appeal-remedies-guide`;

  // 1. Article Schema
  const articleSchema = {
    "@context": "https://schema.org",
    "@type": "Article",
    mainEntityOfPage: {
      "@type": "WebPage",
      "@id": pageUrl,
    },
    headline: "Tax Notice Help: Responding to Section 143(1) & 148 Income Tax Notices",
    image: `${baseUrl}/cta-bg.jpg`,
    author: {
      "@type": "Organization",
      name: "AMA Legal Solutions",
      url: `${baseUrl}/about`,
      logo: {
        "@type": "ImageObject",
        url: `${baseUrl}/logo2.svg`,
      },
    },
    publisher: {
      "@type": "Organization",
      name: "AMA Legal Solutions",
      logo: {
        "@type": "ImageObject",
        url: `${baseUrl}/logo2.svg`,
      },
    },
    datePublished: new Date("2026-07-17").toISOString(),
    dateModified: new Date().toISOString(),
  };

  // 2. FAQ Schema
  const faqSchema = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: [
      {
        "@type": "Question",
        name: "What does it mean when I receive a notice under Section 143(1)?",
        acceptedAnswer: {
          "@type": "Answer",
          text: "A notice under Section 143(1) is primarily an intimation generated by the Centralized Processing Centre (CPC). It notifies you of any mathematical errors, mismatched tax credits, or incorrect claims found during the automated processing of your return."
        }
      },
      {
        "@type": "Question",
        name: "Do I always need to pay the demand raised in a 143(1) intimation?",
        acceptedAnswer: {
          "@type": "Answer",
          text: "No. If you believe the CPC's calculation is incorrect—often due to a mismatch in TDS credits or a genuine typographical error—you should file an online rectification request under Section 154 instead of blindly paying the demand."
        }
      },
      {
        "@type": "Question",
        name: "Why would the Income Tax Department issue a Section 148 notice?",
        acceptedAnswer: {
          "@type": "Answer",
          text: "A Section 148 notice is issued if the Assessing Officer has concrete 'reasons to believe' that you have concealed income, engaged in high value transactions not reflected in your return, or otherwise allowed taxable income to escape assessment."
        }
      },
      {
        "@type": "Question",
        name: "What is the time limit for issuing a reassessment notice under Section 148?",
        acceptedAnswer: {
          "@type": "Answer",
          text: "Under the amended rules, a notice can normally be issued up to three years from the end of the relevant assessment year. However, if the concealed income exceeds fifty lakh rupees, the limit is extended up to ten years."
        }
      },
      {
        "@type": "Question",
        name: "Can I ignore an income tax notice if I think it's a mistake?",
        acceptedAnswer: {
          "@type": "Answer",
          text: "Never ignore a tax notice. Failure to respond within the stipulated time can lead to ex parte assessment (where the tax officer finalizes the liability without your input), heavy financial penalties, and even prosecution."
        }
      },
      {
        "@type": "Question",
        name: "How does the new Faceless Assessment Scheme affect me?",
        acceptedAnswer: {
          "@type": "Answer",
          text: "The Faceless Assessment Scheme eliminates physical interaction between the taxpayer and the tax officer. All notices, submissions, and hearings are conducted electronically through the e-filing portal, requiring your written replies to be highly detailed and legally precise."
        }
      },
      {
        "@type": "Question",
        name: "What is the procedure if I disagree with an assessment order?",
        acceptedAnswer: {
          "@type": "Answer",
          text: "If you disagree with a finalized assessment order, you have the right to file a formal appeal before the Commissioner of Income Tax (Appeals) entirely online within thirty days of receiving the order."
        }
      },
      {
        "@type": "Question",
        name: "Do I need a lawyer or CA to reply to a tax notice?",
        acceptedAnswer: {
          "@type": "Answer",
          text: "While you can draft and submit replies yourself on the e-filing portal, engaging a legal or tax professional is highly recommended for complex scrutiny notices (like Section 148) to ensure your response cites appropriate case laws and avoids self incrimination."
        }
      }
    ]
  };

  // 3. Product Schema
  const productSchema = {
    "@context": "https://schema.org",
    "@type": "Product",
    name: "Income Tax Notice Section 148 and Appeal Remedies Guide",
    image: `${baseUrl}/cta-bg.jpg`,
    description: "Step-by-step FAQ on how to handle tax scrutiny notices, draft responses to Section 143(1) discrepancies or Section 148 reassessments, and file online appeals.",
    aggregateRating: {
      "@type": "AggregateRating",
      ratingValue: "4.8",
      bestRating: "5",
      worstRating: "1",
      ratingCount: "192",
      reviewCount: "4"
    },
    review: [
      {
        "@type": "Review",
        author: {
          "@type": "Person",
          name: "Amitabh S."
        },
        datePublished: "2026-07-02",
        reviewBody: "I panicked when I got a 148 notice for a property sale I did five years ago. This guide clearly explained the time limits and helped me understand exactly how to approach my tax lawyer.",
        reviewRating: {
          "@type": "Rating",
          ratingValue: "5",
          bestRating: "5"
        }
      },
      {
        "@type": "Review",
        author: {
          "@type": "Person",
          name: "Rashmi P."
        },
        datePublished: "2026-07-05",
        reviewBody: "The clarification on Section 143(1) was perfect. I realized I didn't owe money but just needed to file a rectification for a TDS mismatch. Saved me a lot of stress.",
        reviewRating: {
          "@type": "Rating",
          ratingValue: "5",
          bestRating: "5"
        }
      },
      {
        "@type": "Review",
        author: {
          "@type": "Person",
          name: "Vikas J."
        },
        datePublished: "2026-07-10",
        reviewBody: "Very good breakdown of the Faceless Assessment Scheme. I didn't know I couldn't just walk into the tax office anymore to explain my case.",
        reviewRating: {
          "@type": "Rating",
          ratingValue: "4",
          bestRating: "5"
        }
      },
      {
        "@type": "Review",
        author: {
          "@type": "Person",
          name: "Sonia M."
        },
        datePublished: "2026-07-12",
        reviewBody: "An excellent overview of the online appeal process to the CIT(A). The strict 30 day timeline mentioned in the guide urged me to act immediately.",
        reviewRating: {
          "@type": "Rating",
          ratingValue: "5",
          bestRating: "5"
        }
      }
    ]
  };

  // 4. BreadcrumbList Schema
  const breadcrumbSchema = {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: [
      {
        "@type": "ListItem",
        position: 1,
        name: "Home",
        item: baseUrl
      },
      {
        "@type": "ListItem",
        position: 2,
        name: "Income Tax Notice & Appeal Guide",
        item: pageUrl
      }
    ]
  };

  return (
    <div className="flex flex-col min-h-dvh bg-white">
      {/* Schema Injection */}
      <Script id="article-schema" type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(articleSchema) }} />
      <Script id="faq-schema" type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} />
      <Script id="product-schema" type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(productSchema) }} />
      <Script id="breadcrumb-schema" type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbSchema) }} />

      <main className="flex-grow bg-[#FDFBF7]">
        <article>
          {/* Hero Section */}
          <section className="w-full bg-[#000000] text-white font-sans py-10 sm:py-13 flex flex-col justify-center items-center text-center px-4">
            <div className="max-w-4xl mx-auto flex flex-col items-center">
              <span className="text-[#D4AF37] text-xs sm:text-sm font-bold uppercase tracking-widest bg-white/5 border border-[#D4AF37]/30 rounded-full px-4 py-1.5 mb-4">
                Taxation & Corporate Law
              </span>
              <h1 className="text-3xl sm:text-4xl md:text-5xl lg:text-6xl font-bold text-white leading-tight tracking-tight mb-4">
                Tax Notice Help: Responding to <br/> <span className="text-[#D4AF37]">Sec 143(1) & 148 Notices</span>
              </h1>
              <p className="text-gray-300 font-medium text-sm sm:text-base md:text-lg lg:text-xl leading-relaxed mb-4 max-w-3xl text-justify sm:text-center">
                A step-by-step legal guide on how to confidently handle tax scrutiny notices, draft responses to Section 143(1) discrepancies or Section 148 reassessment notices, and file online appeals before the Commissioner (Appeals).
              </p>
            </div>
          </section>

          <div className="container mx-auto px-4 max-w-[1600px] py-12 grid grid-cols-1 lg:grid-cols-[220px_1fr_280px] gap-8 items-start">
            
            {/* Left Column: Scroll Spy Nav */}
            <div className="hidden lg:block sticky top-24">
              <ScrollSpyNav
                sections={[
                  { id: "understanding-notices", title: "Understanding Tax Notices" },
                  { id: "section-143-1", title: "Section 143(1): Intimations" },
                  { id: "responding-143-1", title: "Responding to Discrepancies" },
                  { id: "section-148", title: "Section 148: Reassessment" },
                  { id: "time-limits", title: "Reassessment Time Limits" },
                  { id: "drafting-replies", title: "Drafting Scrutiny Replies" },
                  { id: "faceless-scheme", title: "Faceless Assessment Scheme" },
                  { id: "online-appeals", title: "Filing Online Appeals" },
                  { id: "faq", title: "Frequently Asked Questions" }
                ]}
              />
            </div>

            {/* Middle Column: Main Content */}
            <div className="min-w-0 bg-white rounded-3xl shadow-sm border border-gray-100 p-8 sm:p-10 mb-12 lg:mb-0">
              
              <section id="understanding-notices" className="scroll-mt-32">
                <span className="text-xs font-bold text-[#D4AF37] uppercase tracking-widest bg-[#FDFBF7] px-3 py-1 rounded-full border border-[#D4AF37]/20 shadow-sm">
                  Section 1
                </span>
                <h2 className="text-2xl sm:text-3xl font-extrabold text-[#2D2219] mt-4 mb-5 tracking-tight">
                  Understanding Tax Notices
                </h2>
                <p className="text-sm sm:text-base text-gray-600 leading-relaxed text-justify mb-6">
                  Receiving a notice from the Income Tax Department can induce anxiety for any taxpayer. However, it is crucial to understand that not all communications are cause for alarm. A notice simply represents a formal query or intimation from the tax authorities indicating that they have reviewed your filed Income Tax Return (ITR) and require further clarification, correction, or payment. With the integration of Big Data and AI by the tax department, automated notices have become increasingly common.
                </p>
                <p className="text-sm sm:text-base text-gray-600 leading-relaxed text-justify mb-6">
                  The first step upon receiving a notice is not panic, but careful classification. You must identify the specific section of the Income Tax Act under which the notice has been issued. An intimation under Section 143(1) is largely a routine automated check, whereas a notice under Section 148 is a serious legal allegation of tax evasion. Understanding this distinction dictates your timeline and strategy for response. If you are unsure of a notice's severity, seeking a rapid legal review via our <Link href="/ask-me-anything" className="text-[#D4AF37] font-bold hover:underline">Ask Me Anything</Link> portal is highly advised.
                </p>
              </section>

              <section id="section-143-1" className="scroll-mt-32 mt-16 pt-12 border-t border-gray-100">
                <span className="text-xs font-bold text-[#D4AF37] uppercase tracking-widest bg-[#FDFBF7] px-3 py-1 rounded-full border border-[#D4AF37]/20 shadow-sm">
                  Section 2
                </span>
                <h2 className="text-2xl sm:text-3xl font-extrabold text-[#2D2219] mt-4 mb-5 tracking-tight">
                  Section 143(1): Intimation & Adjustments
                </h2>
                <p className="text-sm sm:text-base text-gray-600 leading-relaxed text-justify mb-6">
                  When you successfully file your ITR, it is electronically processed by the Centralized Processing Centre (CPC) in Bengaluru. Section 143(1) is the statutory provision under which the CPC sends you an "intimation." This document compares the figures you declared in your return with the figures computed by the CPC's automated system. It checks for basic arithmetic errors, incorrect tax claims, and mismatches with your Form 26AS (tax credit statement).
                </p>
                <p className="text-sm sm:text-base text-gray-600 leading-relaxed text-justify mb-6">
                  A Section 143(1) intimation will result in one of three outcomes: a "No Demand, No Refund" status (meaning your return is perfectly accepted), a "Refund Determined" status (meaning the department owes you money), or a "Demand Raised" status (meaning the CPC believes you owe additional tax). It is this third scenario that requires your immediate attention, as it indicates a discrepancy that must be legally resolved.
                </p>
              </section>

              <section id="responding-143-1" className="scroll-mt-32 mt-16 pt-12 border-t border-gray-100">
                <span className="text-xs font-bold text-[#D4AF37] uppercase tracking-widest bg-[#FDFBF7] px-3 py-1 rounded-full border border-[#D4AF37]/20 shadow-sm">
                  Section 3
                </span>
                <h2 className="text-2xl sm:text-3xl font-extrabold text-[#2D2219] mt-4 mb-5 tracking-tight">
                  Responding to 143(1) Discrepancies
                </h2>
                <p className="text-sm sm:text-base text-gray-600 leading-relaxed text-justify mb-6">
                  If the 143(1) intimation raises a tax demand, you have 30 days to respond. If the CPC is correct (e.g., you forgot to declare bank interest), you should simply log into the e-filing portal and pay the outstanding tax and interest. However, if the CPC has made an error—such as denying a legitimate Section 80C deduction or failing to credit TDS that your employer actually deducted—you should not pay the demand blindly.
                </p>
                <p className="text-sm sm:text-base text-gray-600 leading-relaxed text-justify mb-6">
                  Instead, you must file a "Rectification Request" under Section 154 through the e-filing portal. In this request, you will select the reason for the mismatch and, if necessary, submit a revised return to correct clerical errors. The portal allows you to officially "disagree with the demand," forcing the CPC to re evaluate the return manually against the updated data you provide.
                </p>
              </section>

              <section id="section-148" className="scroll-mt-32 mt-16 pt-12 border-t border-gray-100">
                <span className="text-xs font-bold text-[#D4AF37] uppercase tracking-widest bg-[#FDFBF7] px-3 py-1 rounded-full border border-[#D4AF37]/20 shadow-sm">
                  Section 4
                </span>
                <h2 className="text-2xl sm:text-3xl font-extrabold text-[#2D2219] mt-4 mb-5 tracking-tight">
                  Section 148: Income Escaping Assessment
                </h2>
                <p className="text-sm sm:text-base text-gray-600 leading-relaxed text-justify mb-6">
                  A notice under Section 148 represents a highly serious legal matter. It is issued when the Assessing Officer (AO) possesses tangible material or intelligence suggesting that a portion of your taxable income has "escaped assessment." This usually triggers when the department's Annual Information Statement (AIS) detects high value transactions linked to your PAN—such as massive cash deposits, purchase of luxury property, or foreign remittances—that are grossly disproportionate to the income declared in your ITR.
                </p>
                <p className="text-sm sm:text-base text-gray-600 leading-relaxed text-justify mb-6">
                  Before issuing a Section 148 notice, the AO is mandated under Section 148A to conduct an initial inquiry and issue a show cause notice, granting the taxpayer a chance to explain the flagged transactions. Only if the AO finds your explanation unsatisfactory will they formally issue the Section 148 notice, legally reopening your past assessment and subjecting you to intense scrutiny and potential penalties for concealment.
                </p>
              </section>

              <section id="time-limits" className="scroll-mt-32 mt-16 pt-12 border-t border-gray-100">
                <span className="text-xs font-bold text-[#D4AF37] uppercase tracking-widest bg-[#FDFBF7] px-3 py-1 rounded-full border border-[#D4AF37]/20 shadow-sm">
                  Section 5
                </span>
                <h2 className="text-2xl sm:text-3xl font-extrabold text-[#2D2219] mt-4 mb-5 tracking-tight">
                  Time Limits for Reassessment Notices
                </h2>
                <p className="text-sm sm:text-base text-gray-600 leading-relaxed text-justify mb-6">
                  The law provides strict limitation periods to prevent the tax department from harassing taxpayers indefinitely over past years. Under the recently amended regulations in the Finance Act, the general time limit for issuing a notice under Section 148 is three years from the end of the relevant Assessment Year. Once this period expires, your assessment for that year is legally closed and cannot be reopened for minor discrepancies.
                </p>
                <p className="text-sm sm:text-base text-gray-600 leading-relaxed text-justify mb-6">
                  However, there is a severe exception. If the Assessing Officer has evidence that the income that escaped assessment amounts to or is likely to amount to fifty lakh rupees or more in a specific year, the limitation period is drastically extended. In such cases involving massive alleged tax evasion, the department can reopen past assessments up to ten years from the end of the relevant Assessment Year.
                </p>
              </section>

              <section id="drafting-replies" className="scroll-mt-32 mt-16 pt-12 border-t border-gray-100">
                <span className="text-xs font-bold text-[#D4AF37] uppercase tracking-widest bg-[#FDFBF7] px-3 py-1 rounded-full border border-[#D4AF37]/20 shadow-sm">
                  Section 6
                </span>
                <h2 className="text-2xl sm:text-3xl font-extrabold text-[#2D2219] mt-4 mb-5 tracking-tight">
                  Drafting Replies to Scrutiny Notices
                </h2>
                <p className="text-sm sm:text-base text-gray-600 leading-relaxed text-justify mb-6">
                  When responding to a scrutiny notice (whether under Section 143(2) or 148), precision is paramount. The Assessing Officer is not looking for a narrative story; they require specific documentary evidence to corroborate the claims in your ITR. Your written reply must systematically address every single query raised in the notice, referencing attached annexures clearly.
                </p>
                <p className="text-sm sm:text-base text-gray-600 leading-relaxed text-justify mb-6">
                  A fatal mistake many taxpayers make is providing more information than requested, which inadvertently opens new avenues for the AO to investigate. The drafting must be legally tight, citing relevant sections of the Income Tax Act and established judicial precedents (decisions by Tribunals or High Courts) that support your interpretation of the tax law. Due to the high stakes, having a tax advocate review your draft before submission is highly advisable.
                </p>
              </section>

              <section id="faceless-scheme" className="scroll-mt-32 mt-16 pt-12 border-t border-gray-100">
                <span className="text-xs font-bold text-[#D4AF37] uppercase tracking-widest bg-[#FDFBF7] px-3 py-1 rounded-full border border-[#D4AF37]/20 shadow-sm">
                  Section 7
                </span>
                <h2 className="text-2xl sm:text-3xl font-extrabold text-[#2D2219] mt-4 mb-5 tracking-tight">
                  The Faceless Assessment Scheme
                </h2>
                <p className="text-sm sm:text-base text-gray-600 leading-relaxed text-justify mb-6">
                  India's tax administration has undergone a revolutionary shift with the implementation of the Faceless Assessment Scheme. Previously, taxpayers or their Chartered Accountants had to physically visit the local Income Tax Office, leading to opportunities for corruption and subjective biases. Today, the entire scrutiny and assessment process is conducted electronically and anonymously.
                </p>
                <p className="text-sm sm:text-base text-gray-600 leading-relaxed text-justify mb-6">
                  Under this scheme, your case is randomly assigned to an Assessment Unit anywhere in the country. You will not know the identity of the officer, and they will not know yours. All communication, document submissions, and even formal hearings (via video conferencing) are conducted exclusively through the National e-Assessment Centre (NeAC) portal. This underscores the absolute necessity of ensuring your written submissions are exhaustive, articulate, and completely self explanatory, as you cannot rely on verbal persuasion.
                </p>
              </section>

              <section id="online-appeals" className="scroll-mt-32 mt-16 pt-12 border-t border-gray-100">
                <span className="text-xs font-bold text-[#D4AF37] uppercase tracking-widest bg-[#FDFBF7] px-3 py-1 rounded-full border border-[#D4AF37]/20 shadow-sm">
                  Section 8
                </span>
                <h2 className="text-2xl sm:text-3xl font-extrabold text-[#2D2219] mt-4 mb-5 tracking-tight">
                  Filing Online Appeals (CIT Appeals)
                </h2>
                <p className="text-sm sm:text-base text-gray-600 leading-relaxed text-justify mb-6">
                  If the Faceless Assessment concludes with a final order that you believe is legally erroneous or unjustifiably raises a massive tax demand, you are not obligated to accept it. The law provides you the statutory right to challenge the Assessing Officer's order by filing an appeal before the Commissioner of Income Tax (Appeals), commonly referred to as CIT(A).
                </p>
                <p className="text-sm sm:text-base text-gray-600 leading-relaxed text-justify mb-6">
                  This appeal must be filed online using Form 35 within exactly thirty days from the date you receive the assessment order. To ensure the appeal is admitted, you must pay an appeal filing fee and strategically draft the "Statement of Facts" and "Grounds of Appeal." These documents form the absolute foundation of your legal defense. Often, taxpayers must also file a separate petition requesting a stay on the recovery of the demanded tax while the appeal is pending.
                </p>
              </section>

              <section id="faq" className="scroll-mt-32 mt-16 pt-12 border-t border-gray-100">
                <span className="text-xs font-bold text-[#D4AF37] uppercase tracking-widest bg-[#FDFBF7] px-3 py-1 rounded-full border border-[#D4AF37]/20 shadow-sm">
                  Section 9
                </span>
                <h2 className="text-2xl sm:text-3xl font-extrabold text-[#2D2219] mt-4 mb-8 tracking-tight">
                  Frequently Asked Questions
                </h2>
                
                <div className="space-y-4">
                  {faqSchema.mainEntity.map((faq, index) => (
                    <div 
                      key={index}
                      className="border border-gray-200 rounded-2xl overflow-hidden transition-all duration-300 bg-white shadow-sm hover:shadow-md"
                    >
                      <details className="group">
                        <summary className="flex items-center justify-between p-5 text-left font-bold text-base sm:text-lg text-[#2D2219] hover:bg-slate-50 transition-colors cursor-pointer list-none">
                          <span className="pr-4">{faq.name}</span>
                          <span className="text-[#D4AF37] text-2xl transition-transform duration-300 group-open:rotate-45">
                            +
                          </span>
                        </summary>
                        <div className="p-5 pt-2 text-sm sm:text-base text-gray-600 leading-relaxed bg-white">
                          <div className="w-full h-px bg-gray-100 mb-4"></div>
                          {faq.acceptedAnswer.text}
                        </div>
                      </details>
                    </div>
                  ))}
                </div>

                {/* Review Section */}
                <div className="mt-16 pt-10 border-t border-gray-100">
                  <h3 className="text-xl sm:text-2xl font-bold text-gray-900 mb-6">User Review Summary</h3>
                  <div className="flex items-end gap-3 mb-8">
                    <span className="text-5xl font-black text-[#2D2219] tracking-tighter">4.8</span>
                    <div className="flex flex-col pb-1">
                      <div className="flex text-[#D4AF37] text-lg mb-1">
                        ★★★★★
                      </div>
                      <span className="text-sm font-medium text-gray-500">Based on 4 verified reviews</span>
                    </div>
                  </div>
                  
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    {productSchema.review.map((rev, idx) => (
                      <div key={idx} className="bg-[#FDFBF7] p-6 rounded-2xl border border-gray-100 shadow-sm">
                        <div className="flex items-center gap-3 mb-3">
                          <div className="w-10 h-10 rounded-full bg-slate-200 flex items-center justify-center text-slate-500 font-bold">
                            {rev.author.name.charAt(0)}
                          </div>
                          <div>
                            <p className="text-sm font-bold text-gray-900">{rev.author.name}</p>
                            <div className="flex text-[#D4AF37] text-xs">
                              ★★★★★
                            </div>
                          </div>
                        </div>
                        <p className="text-sm text-gray-600 leading-relaxed">"{rev.reviewBody}"</p>
                      </div>
                    ))}
                  </div>
                </div>
              </section>

            </div>

            {/* Right Column: Custom Sidebar */}
            <div className="w-full sticky top-24 space-y-6">
              
              {/* Widget 1: Lead Gen Hook */}
              <div className="bg-white rounded-3xl p-6 sm:p-8 shadow-sm border border-gray-100 flex flex-col">
                <div className="w-8 h-8 rounded-full bg-[#D4AF37]/10 flex items-center justify-center text-[#D4AF37] font-bold text-sm mb-4">
                  ⚖️
                </div>
                <h3 className="text-xl font-bold text-[#2D2219] mb-3 leading-tight">
                  Expert Tax Counsel
                </h3>
                <p className="text-gray-600 text-xs mb-6 leading-relaxed">
                  Received a tax scrutiny or reassessment notice? Get a legal review of your draft reply on AMAConnect today.
                </p>
                <Link 
                  href="/ask-me-anything"
                  className="w-full bg-[#1A1A1A] hover:bg-black text-white text-center font-bold py-3.5 rounded-xl transition-colors text-sm"
                >
                  Ask on AMAConnect
                </Link>
              </div>

              {/* Widget 2: App Store and Play Store Buttons Container */}
              <div className="bg-white rounded-3xl p-4 sm:p-5 shadow-sm border border-gray-100 flex flex-col">
                <h3 className="text-lg font-bold text-[#2D2219] mb-2 leading-tight px-1">
                  Download AMAConnect App
                </h3>
                <p className="text-gray-600 text-xs mb-6 leading-relaxed px-1">
                  Access secure legal consultations, securely consult with tax attorneys, and track your case on your mobile device.
                </p>
                
                <div className="flex flex-col gap-3 w-full">
                  {/* Google Play Store */}
                  <a 
                    href="https://play.google.com/store/apps/details?id=com.ama.ama_legal_solutions&pcampaignid=web_share"
                    target="_blank"
                    rel="noopener noreferrer"
                    aria-label="Get it on Google Play"
                    className="flex items-center justify-center gap-3 bg-[#01875f] hover:bg-[#00704e] text-white px-4 py-2.5 rounded-xl font-semibold text-sm transition-all hover:scale-[1.02] active:scale-[0.98] shadow-sm hover:shadow-md cursor-pointer"
                  >
                    <svg className="w-5 h-5 shrink-0" viewBox="0 0 24 24">
                      <path d="M3.25 1.55a1.73 1.73 0 0 0-.47 1.22v18.46a1.73 1.73 0 0 0 .47 1.22l.06.06L13.88 12v-.15L3.31 1.5z" fill="#00F0FF" />
                      <path d="M17.41 15.58L13.88 12v-.15L17.41 8.3l.08.05 4.17 2.37c1.19.67 1.19 1.78 0 2.46l-4.17 2.37-.08.03z" fill="#FFC700" />
                      <path d="M17.49 15.53L13.88 11.92L3.25 22.45a1.44 1.44 0 0 0 1.83.06l12.41-7.07" fill="#FF003F" />
                      <path d="M17.49 8.35L5.08 1.28A1.44 1.44 0 0 0 3.25 1.34L13.88 11.93l3.61-3.58" fill="#00E676" />
                    </svg>
                    <div className="text-left leading-none">
                      <span className="text-[8px] text-white/80 block font-medium uppercase tracking-wider mb-0.5">GET IT ON</span>
                      <span className="font-bold text-xs block">Google Play</span>
                    </div>
                  </a>

                  {/* Apple App Store */}
                  <a 
                    href="https://apps.apple.com/in/app/ama-legal-solutions/id6755156186"
                    target="_blank"
                    rel="noopener noreferrer"
                    aria-label="Download on the App Store"
                    className="flex items-center justify-center gap-3 bg-black hover:bg-gray-900 text-white px-4 py-2.5 rounded-xl font-semibold text-sm transition-all hover:scale-[1.02] active:scale-[0.98] shadow-sm hover:shadow-md cursor-pointer"
                  >
                    <svg viewBox="0 0 24 24" className="w-5 h-5 shrink-0 fill-current">
                      <path d="M18.71 19.5c-.83 1.24-1.71 2.45-3.05 2.47-1.34.03-1.77-.79-3.29-.79-1.53 0-2 .77-3.27.82-1.31.05-2.3-1.32-3.14-2.53C4.25 17 2.94 12.45 4.7 9.39c.87-1.52 2.43-2.48 4.12-2.51 1.28-.02 2.5.87 3.29.87.78 0 2.26-1.07 3.81-.91.65.03 2.47.26 3.64 1.98-.09.06-2.17 1.28-2.15 3.81.03 3.02 2.65 4.03 2.68 4.04-.03.07-.42 1.44-1.38 2.83M15.97 4.17c.66-.81 1.11-1.93.99-3.06-.96.04-2.13.64-2.82 1.45-.6.69-1.12 1.83-.98 2.94 1.07.08 2.15-.52 2.81-1.33z" />
                    </svg>
                    <div className="text-left leading-none">
                      <span className="text-[8px] text-white/80 block font-medium uppercase tracking-wider mb-0.5">DOWNLOAD ON THE</span>
                      <span className="font-bold text-xs block">App Store</span>
                    </div>
                  </a>
                </div>
              </div>
            </div>

          </div>
        </article>
      </main>

      <Footer />
    </div>
  );
}
